// Classes and structures being serialized

// Generated by ProtocolBuffer
// - a pure c# code generation implementation of protocol buffers
// Report bugs to: https://silentorbit.com/protobuf/

// DO NOT EDIT
// This file will be overwritten when CodeGenerator is run.
// To make custom modifications, edit the .proto file and add //:external before the message line
// then write the code and the changes in a separate file.
using System;
using System.Collections.Generic;

namespace Msg
{
    public partial class QuickRegister
    {
        /// <summary>注册账号</summary>
        public string Account { get; set; }
        public bool hasAccount = false;
        
        /// <summary>密码</summary>
        public string Passwd { get; set; }
        public bool hasPasswd = false;
        
        // ProtocolBuffers wire field id
        public const int AccountFieldID = 1;
        public const int PasswdFieldID = 2;
    }
    
    public partial class GameServer
    {
        public string Ip { get; set; }
        public bool hasIp = false;
        
        public uint Port { get; set; }
        public bool hasPort = false;
        
        // ProtocolBuffers wire field id
        public const int IpFieldID = 1;
        public const int PortFieldID = 2;
    }
    
    public partial class RString
    {
        public string Str { get; set; }
        public bool hasStr = false;
        
        // ProtocolBuffers wire field id
        public const int StrFieldID = 1;
    }
    
    public partial class MsgTip
    {
        /// <summary>提示编号</summary>
        public uint Tip { get; set; }
        public bool hasTip = false;
        
        /// <summary>提示链接值 备用</summary>
        public List<string> Value { get; set; }
        public bool hasValue = false;
        
        /// <summary>提示类型 1是只有确定的窗口，2是有确定和取消窗口,3走马灯</summary>
        public uint Type { get; set; }
        public bool hasType = false;
        
        // ProtocolBuffers wire field id
        public const int TipFieldID = 1;
        public const int ValueFieldID = 2;
        public const int TypeFieldID = 3;
    }
    
    public partial class SrvVersion
    {
        public string Version { get; set; }
        public bool hasVersion = false;
        
        // ProtocolBuffers wire field id
        public const int VersionFieldID = 1;
    }
    
    public partial class Login
    {
        /// <summary>用户账号</summary>
        public string Account { get; set; }
        public bool hasAccount = false;
        
        /// <summary>密码</summary>
        public string Password { get; set; }
        public bool hasPassword = false;
        
        /// <summary>登录返回结果：200登录成功，101账号不存在，102密码错误，103登录异常</summary>
        public int Result { get; set; }
        public bool hasResult = false;
        
        /// <summary>游客登录发送</summary>
        public uint Accid { get; set; }
        public bool hasAccid = false;
        
        /// <summary>登录时间</summary>
        public uint Logintime { get; set; }
        public bool hasLogintime = false;
        
        /// <summary>登录平台编号：0 PC，101 google</summary>
        public uint Pf { get; set; }
        public bool hasPf = false;
        
        // ProtocolBuffers wire field id
        public const int AccountFieldID = 1;
        public const int PasswordFieldID = 2;
        public const int ResultFieldID = 3;
        public const int AccidFieldID = 4;
        public const int LogintimeFieldID = 5;
        public const int PfFieldID = 6;
    }
    
    public partial class Server
    {
        public uint _Id { get; set; }
        public bool has_Id = false;
        
        public string Ip { get; set; }
        public bool hasIp = false;
        
        public uint Port { get; set; }
        public bool hasPort = false;
        
        public string Node { get; set; }
        public bool hasNode = false;
        
        public uint Type { get; set; }
        public bool hasType = false;
        
        public uint Num { get; set; }
        public bool hasNum = false;
        
        public uint Flag { get; set; }
        public bool hasFlag = false;
        
        public string Name { get; set; }
        public bool hasName = false;
        
        // ProtocolBuffers wire field id
        public const int _IdFieldID = 1;
        public const int IpFieldID = 2;
        public const int PortFieldID = 3;
        public const int NodeFieldID = 4;
        public const int TypeFieldID = 5;
        public const int NumFieldID = 6;
        public const int FlagFieldID = 7;
        public const int NameFieldID = 8;
    }
    
    public partial class MsgServerTime
    {
        public uint Servertime { get; set; }
        public bool hasServertime = false;
        
        /// <summary>开服时间</summary>
        public uint StartTime { get; set; }
        public bool hasStartTime = false;
        
        // ProtocolBuffers wire field id
        public const int ServertimeFieldID = 1;
        public const int StartTimeFieldID = 2;
    }
    
    public partial class Property
    {
        /// <summary>属性类型：1篮筐减速，2自动生产，减时间等</summary>
        public uint Type { get; set; }
        public bool hasType = false;
        
        /// <summary>属性值</summary>
        public uint Value { get; set; }
        public bool hasValue = false;
        
        // ProtocolBuffers wire field id
        public const int TypeFieldID = 1;
        public const int ValueFieldID = 2;
    }
    
    public partial class PlayerInfo
    {
        /// <summary>玩家账号</summary>
        public string Account { get; set; }
        public bool hasAccount = false;
        
        /// <summary>昵称</summary>
        public string Nickname { get; set; }
        public bool hasNickname = false;
        
        /// <summary>当前金币数</summary>
        public uint Gold { get; set; }
        public bool hasGold = false;
        
        /// <summary>头像</summary>
        public uint Head { get; set; }
        public bool hasHead = false;
        
        /// <summary>账号数字编号</summary>
        public uint Accid { get; set; }
        public bool hasAccid = false;
        
        /// <summary>角色数字编号</summary>
        public uint PlayerId { get; set; }
        public bool hasPlayerId = false;
        
        /// <summary>经验</summary>
        public float Exp { get; set; }
        public bool hasExp = false;
        
        /// <summary>等级</summary>
        public uint Lv { get; set; }
        public bool hasLv = false;
        
        /// <summary>vip经验</summary>
        public float VipExp { get; set; }
        public bool hasVipExp = false;
        
        /// <summary>vip等级</summary>
        public uint VipLv { get; set; }
        public bool hasVipLv = false;
        
        /// <summary>服装</summary>
        public uint Dress { get; set; }
        public bool hasDress = false;
        
        /// <summary>彩金池</summary>
        public ulong Pool { get; set; }
        public bool hasPool = false;
        
        /// <summary>游戏属性</summary>
        public List<Msg.Property> Prob { get; set; }
        public bool hasProb = false;
        
        /// <summary>解锁的面值</summary>
        public List<uint> UnlockGold { get; set; }
        public bool hasUnlockGold = false;
        
        /// <summary>解锁的倍率</summary>
        public List<uint> UnlockRate { get; set; }
        public bool hasUnlockRate = false;
        
        /// <summary>解锁的衣服</summary>
        public List<uint> UnlockClothes { get; set; }
        public bool hasUnlockClothes = false;
        
        /// <summary>解锁到的关卡</summary>
        public uint MapId { get; set; }
        public bool hasMapId = false;
        
        /// <summary>0新玩家,1老玩家</summary>
        public uint IsNew { get; set; }
        public bool hasIsNew = false;
        
        /// <summary>今天第一次登录0 不是，1是</summary>
        public uint IsFirstLogin { get; set; }
        public bool hasIsFirstLogin = false;
        
        /// <summary>签到:0已签，1未签</summary>
        public uint Sign { get; set; }
        public bool hasSign = false;
        
        /// <summary>在线定时金币</summary>
        public uint TimeGold { get; set; }
        public bool hasTimeGold = false;
        
        /// <summary>新手引导</summary>
        public uint Guide { get; set; }
        public bool hasGuide = false;
        
        /// <summary>定时免费金币的下一次领取时间：</summary>
        public uint FreeTime { get; set; }
        public bool hasFreeTime = false;
        
        public uint VipGift { get; set; }
        public bool hasVipGift = false;
        
        /// <summary>0登录，1掉线重连</summary>
        public uint Relogin { get; set; }
        public bool hasRelogin = false;
        
        // ProtocolBuffers wire field id
        public const int AccountFieldID = 1;
        public const int NicknameFieldID = 2;
        public const int GoldFieldID = 3;
        public const int HeadFieldID = 4;
        public const int AccidFieldID = 5;
        public const int PlayerIdFieldID = 6;
        public const int ExpFieldID = 7;
        public const int LvFieldID = 8;
        public const int VipExpFieldID = 9;
        public const int VipLvFieldID = 10;
        public const int DressFieldID = 11;
        public const int PoolFieldID = 12;
        public const int ProbFieldID = 13;
        public const int UnlockGoldFieldID = 14;
        public const int UnlockRateFieldID = 15;
        public const int UnlockClothesFieldID = 16;
        public const int MapIdFieldID = 17;
        public const int IsNewFieldID = 18;
        public const int IsFirstLoginFieldID = 19;
        public const int SignFieldID = 20;
        public const int TimeGoldFieldID = 21;
        public const int GuideFieldID = 22;
        public const int FreeTimeFieldID = 23;
        public const int VipGiftFieldID = 24;
        public const int ReloginFieldID = 25;
    }
    
    /// <summary>角色详细统计数据</summary>
    public partial class PlayerDetail
    {
        public string _Id { get; set; }
        public bool has_Id = false;
        
        /// <summary>玩家id</summary>
        public uint PlayerId { get; set; }
        public bool hasPlayerId = false;
        
        /// <summary>最高持有金币</summary>
        public uint MostCoinCount { get; set; }
        public bool hasMostCoinCount = false;
        
        /// <summary>累计获得金币</summary>
        public uint CollectCoinCount { get; set; }
        public bool hasCollectCoinCount = false;
        
        /// <summary>购买服饰数量</summary>
        public uint GetClothCount { get; set; }
        public bool hasGetClothCount = false;
        
        /// <summary>累计消耗金币</summary>
        public uint CostCoinCount { get; set; }
        public bool hasCostCoinCount = false;
        
        /// <summary>累计投放金币</summary>
        public uint PutCoinCount { get; set; }
        public bool hasPutCoinCount = false;
        
        /// <summary>多倍收集的次数</summary>
        public uint PowerCoinTimes { get; set; }
        public bool hasPowerCoinTimes = false;
        
        /// <summary>一推到底次数</summary>
        public uint PushAllTimes { get; set; }
        public bool hasPushAllTimes = false;
        
        /// <summary>护墙次数</summary>
        public uint WallTimes { get; set; }
        public bool hasWallTimes = false;
        
        /// <summary>冰地技能次数</summary>
        public uint FreezeCollectionCount { get; set; }
        public bool hasFreezeCollectionCount = false;
        
        /// <summary>加速技能次数</summary>
        public uint AccelerateCollectionCount { get; set; }
        public bool hasAccelerateCollectionCount = false;
        
        /// <summary>震动技能次数</summary>
        public uint SharkCollectionCount { get; set; }
        public bool hasSharkCollectionCount = false;
        
        /// <summary>收集50金币次数</summary>
        public uint FiftyTime { get; set; }
        public bool hasFiftyTime = false;
        
        /// <summary>收集100金币次数</summary>
        public uint HundredTime { get; set; }
        public bool hasHundredTime = false;
        
        /// <summary>收集300金币次数</summary>
        public uint ThreeHundredTime { get; set; }
        public bool hasThreeHundredTime = false;
        
        /// <summary>收集500金币次数</summary>
        public uint FiveHundredTime { get; set; }
        public bool hasFiveHundredTime = false;
        
        /// <summary>打击乌鸦次数</summary>
        public uint HitCrowTimes { get; set; }
        public bool hasHitCrowTimes = false;
        
        /// <summary>获得15秒免费次数</summary>
        public uint FiftyFreeTime { get; set; }
        public bool hasFiftyFreeTime = false;
        
        /// <summary>20秒免费次数</summary>
        public uint TwentyFreeTime { get; set; }
        public bool hasTwentyFreeTime = false;
        
        /// <summary>彩金转盘次数</summary>
        public uint SuperDrawTimes { get; set; }
        public bool hasSuperDrawTimes = false;
        
        /// <summary>转盘次数</summary>
        public uint RotateTimes { get; set; }
        public bool hasRotateTimes = false;
        
        // ProtocolBuffers wire field id
        public const int _IdFieldID = 1;
        public const int PlayerIdFieldID = 2;
        public const int MostCoinCountFieldID = 3;
        public const int CollectCoinCountFieldID = 4;
        public const int GetClothCountFieldID = 5;
        public const int CostCoinCountFieldID = 6;
        public const int PutCoinCountFieldID = 7;
        public const int PowerCoinTimesFieldID = 8;
        public const int PushAllTimesFieldID = 9;
        public const int WallTimesFieldID = 10;
        public const int FreezeCollectionCountFieldID = 11;
        public const int AccelerateCollectionCountFieldID = 12;
        public const int SharkCollectionCountFieldID = 13;
        public const int FiftyTimeFieldID = 14;
        public const int HundredTimeFieldID = 15;
        public const int ThreeHundredTimeFieldID = 16;
        public const int FiveHundredTimeFieldID = 17;
        public const int HitCrowTimesFieldID = 18;
        public const int FiftyFreeTimeFieldID = 19;
        public const int TwentyFreeTimeFieldID = 20;
        public const int SuperDrawTimesFieldID = 21;
        public const int RotateTimesFieldID = 22;
    }
    
    public partial class CreatePlayer
    {
        public uint Accid { get; set; }
        public bool hasAccid = false;
        
        /// <summary>创建角色名字</summary>
        public string Name { get; set; }
        public bool hasName = false;
        
        /// <summary>性别</summary>
        public uint Gender { get; set; }
        public bool hasGender = false;
        
        /// <summary>result = 1创建角色，2创建失败（昵称已经存在）,3系统异常</summary>
        public uint Result { get; set; }
        public bool hasResult = false;
        
        // ProtocolBuffers wire field id
        public const int AccidFieldID = 1;
        public const int NameFieldID = 2;
        public const int GenderFieldID = 3;
        public const int ResultFieldID = 4;
    }
    
    public partial class VipInfo
    {
        public string _Id { get; set; }
        public bool has_Id = false;
        
        /// <summary>玩家id</summary>
        public uint PlayerId { get; set; }
        public bool hasPlayerId = false;
        
        /// <summary>玩家vip等级</summary>
        public uint Lv { get; set; }
        public bool hasLv = false;
        
        /// <summary>玩家vip经验</summary>
        public uint Exp { get; set; }
        public bool hasExp = false;
        
        /// <summary>总充值</summary>
        public uint Rmb { get; set; }
        public bool hasRmb = false;
        
        // ProtocolBuffers wire field id
        public const int _IdFieldID = 1;
        public const int PlayerIdFieldID = 2;
        public const int LvFieldID = 3;
        public const int ExpFieldID = 4;
        public const int RmbFieldID = 5;
    }
    
    public partial class Item
    {
        public string _Id { get; set; }
        public bool has_Id = false;
        
        /// <summary>玩家id</summary>
        public uint PlayerId { get; set; }
        public bool hasPlayerId = false;
        
        /// <summary>道具编号</summary>
        public uint Id { get; set; }
        public bool hasId = false;
        
        /// <summary>道具数量</summary>
        public uint Num { get; set; }
        public bool hasNum = false;
        
        // ProtocolBuffers wire field id
        public const int _IdFieldID = 1;
        public const int PlayerIdFieldID = 2;
        public const int IdFieldID = 3;
        public const int NumFieldID = 4;
    }
    
    public partial class ItemData
    {
        public List<Msg.Item> Items { get; set; }
        public bool hasItems = false;
        
        // ProtocolBuffers wire field id
        public const int ItemsFieldID = 1;
    }
    
    public partial class DeleteItem
    {
        public uint Id { get; set; }
        public bool hasId = false;
        
        // ProtocolBuffers wire field id
        public const int IdFieldID = 1;
    }
    
    public partial class UseItem
    {
        public uint Id { get; set; }
        public bool hasId = false;
        
        public uint Num { get; set; }
        public bool hasNum = false;
        
        /// <summary>使用结果：1使用成功，0使用失败</summary>
        public uint Result { get; set; }
        public bool hasResult = false;
        
        // ProtocolBuffers wire field id
        public const int IdFieldID = 1;
        public const int NumFieldID = 2;
        public const int ResultFieldID = 3;
    }
    
    public partial class BuyItem
    {
        public uint Id { get; set; }
        public bool hasId = false;
        
        // ProtocolBuffers wire field id
        public const int IdFieldID = 1;
    }
    
    public partial class Email
    {
        public string _Id { get; set; }
        public bool has_Id = false;
        
        /// <summary>邮件编号</summary>
        public uint EmailId { get; set; }
        public bool hasEmailId = false;
        
        /// <summary>发送者网络id</summary>
        public uint Fid { get; set; }
        public bool hasFid = false;
        
        /// <summary>发送者名字</summary>
        public string Fname { get; set; }
        public bool hasFname = false;
        
        /// <summary>接收者网络id</summary>
        public uint Rid { get; set; }
        public bool hasRid = false;
        
        /// <summary>接收者名字</summary>
        public string Rname { get; set; }
        public bool hasRname = false;
        
        /// <summary>邮件标题</summary>
        public string Title { get; set; }
        public bool hasTitle = false;
        
        /// <summary>邮件内容</summary>
        public string Content { get; set; }
        public bool hasContent = false;
        
        /// <summary>邮件附件</summary>
        public List<Msg.Item> Items { get; set; }
        public bool hasItems = false;
        
        /// <summary>邮件状态</summary>
        public uint State { get; set; }
        public bool hasState = false;
        
        /// <summary>邮件查看后延迟删除时间</summary>
        public uint Delaytime { get; set; }
        public bool hasDelaytime = false;
        
        /// <summary>邮件读取时间</summary>
        public uint Readtime { get; set; }
        public bool hasReadtime = false;
        
        /// <summary>邮件创建时间</summary>
        public uint Createtime { get; set; }
        public bool hasCreatetime = false;
        
        /// <summary>邮件总存活时间</summary>
        public uint Lifetime { get; set; }
        public bool hasLifetime = false;
        
        /// <summary>邮件类型 1普通邮件，2公告</summary>
        public uint Type { get; set; }
        public bool hasType = false;
        
        // ProtocolBuffers wire field id
        public const int _IdFieldID = 1;
        public const int EmailIdFieldID = 2;
        public const int FidFieldID = 3;
        public const int FnameFieldID = 4;
        public const int RidFieldID = 5;
        public const int RnameFieldID = 6;
        public const int TitleFieldID = 7;
        public const int ContentFieldID = 8;
        public const int ItemsFieldID = 9;
        public const int StateFieldID = 10;
        public const int DelaytimeFieldID = 11;
        public const int ReadtimeFieldID = 12;
        public const int CreatetimeFieldID = 13;
        public const int LifetimeFieldID = 14;
        public const int TypeFieldID = 15;
    }
    
    public partial class EmailData
    {
        public List<Msg.Email> Emails { get; set; }
        public bool hasEmails = false;
        
        // ProtocolBuffers wire field id
        public const int EmailsFieldID = 1;
    }
    
    public partial class ReadEmail
    {
        public uint Id { get; set; }
        public bool hasId = false;
        
        // ProtocolBuffers wire field id
        public const int IdFieldID = 1;
    }
    
    public partial class GetEmailItem
    {
        public uint Id { get; set; }
        public bool hasId = false;
        
        // ProtocolBuffers wire field id
        public const int IdFieldID = 1;
    }
    
    public partial class DeleteEmail
    {
        public uint Id { get; set; }
        public bool hasId = false;
        
        // ProtocolBuffers wire field id
        public const int IdFieldID = 1;
    }
    
    public partial class ModifyHead
    {
        public uint Id { get; set; }
        public bool hasId = false;
        
        // ProtocolBuffers wire field id
        public const int IdFieldID = 1;
    }
    
    public partial class ModifyNickName
    {
        public string Name { get; set; }
        public bool hasName = false;
        
        // ProtocolBuffers wire field id
        public const int NameFieldID = 1;
    }
    
    public partial class Rotate
    {
        public uint Id { get; set; }
        public bool hasId = false;
        
        // ProtocolBuffers wire field id
        public const int IdFieldID = 1;
    }
    
    public partial class Sign
    {
        public uint Week { get; set; }
        public bool hasWeek = false;
        
        public uint State { get; set; }
        public bool hasState = false;
        
        public uint Value { get; set; }
        public bool hasValue = false;
        
        // ProtocolBuffers wire field id
        public const int WeekFieldID = 1;
        public const int StateFieldID = 2;
        public const int ValueFieldID = 3;
    }
    
    public partial class SignInfo
    {
        public string _Id { get; set; }
        public bool has_Id = false;
        
        public uint PlayerId { get; set; }
        public bool hasPlayerId = false;
        
        public List<Msg.Sign> Sign { get; set; }
        public bool hasSign = false;
        
        // ProtocolBuffers wire field id
        public const int _IdFieldID = 1;
        public const int PlayerIdFieldID = 2;
        public const int SignFieldID = 3;
    }
    
    public partial class BGold
    {
        public uint Gold { get; set; }
        public bool hasGold = false;
        
        public uint Num { get; set; }
        public bool hasNum = false;
        
        // ProtocolBuffers wire field id
        public const int GoldFieldID = 1;
        public const int NumFieldID = 2;
    }
    
    public partial class BoardGold
    {
        /// <summary>金币来源:1初始化,2投入，3彩金。。。</summary>
        public uint Type { get; set; }
        public bool hasType = false;
        
        public List<Msg.BGold> Golds { get; set; }
        public bool hasGolds = false;
        
        // ProtocolBuffers wire field id
        public const int TypeFieldID = 1;
        public const int GoldsFieldID = 2;
    }
    
    public partial class Coin
    {
        /// <summary>金币的网络id</summary>
        public uint Id { get; set; }
        public bool hasId = false;
        
        /// <summary>金币的面值：</summary>
        public uint Gold { get; set; }
        public bool hasGold = false;
        
        /// <summary>金币来源   2001</summary>
        public uint Type { get; set; }
        public bool hasType = false;
        
        /// <summary>出现位置x</summary>
        public float X { get; set; }
        public bool hasX = false;
        
        /// <summary>出现位置y</summary>
        public float Y { get; set; }
        public bool hasY = false;
        
        /// <summary>出现位置z</summary>
        public float Z { get; set; }
        public bool hasZ = false;
        
        /// <summary>coin状态:0,1不能再投中</summary>
        public uint State { get; set; }
        public bool hasState = false;
        
        // ProtocolBuffers wire field id
        public const int IdFieldID = 1;
        public const int GoldFieldID = 2;
        public const int TypeFieldID = 3;
        public const int XFieldID = 4;
        public const int YFieldID = 5;
        public const int ZFieldID = 6;
        public const int StateFieldID = 7;
    }
    
    public partial class Map
    {
        public string _Id { get; set; }
        public bool has_Id = false;
        
        /// <summary>玩家编号</summary>
        public uint PlayerId { get; set; }
        public bool hasPlayerId = false;
        
        /// <summary>地图编号</summary>
        public uint MapId { get; set; }
        public bool hasMapId = false;
        
        /// <summary>是否解锁0,未解锁，1解锁</summary>
        public uint Lock { get; set; }
        public bool hasLock = false;
        
        /// <summary>收集金币数</summary>
        public uint CollectGold { get; set; }
        public bool hasCollectGold = false;
        
        /// <summary>投入金币数 值为0时表示首次进入关卡</summary>
        public uint ShotGold { get; set; }
        public bool hasShotGold = false;
        
        /// <summary>桌上金币值</summary>
        public uint BoardGold { get; set; }
        public bool hasBoardGold = false;
        
        /// <summary>桌上金币分布</summary>
        public List<Msg.Coin> Coins { get; set; }
        public bool hasCoins = false;
        
        /// <summary>摇滚分值   满20分自动转</summary>
        public uint RotateScore { get; set; }
        public bool hasRotateScore = false;
        
        /// <summary>是否初始化 0初始化  1不初始化</summary>
        public uint Flag { get; set; }
        public bool hasFlag = false;
        
        /// <summary>关卡奖励0未领取，1已领取</summary>
        public uint Reward { get; set; }
        public bool hasReward = false;
        
        // ProtocolBuffers wire field id
        public const int _IdFieldID = 1;
        public const int PlayerIdFieldID = 2;
        public const int MapIdFieldID = 3;
        public const int LockFieldID = 4;
        public const int CollectGoldFieldID = 5;
        public const int ShotGoldFieldID = 6;
        public const int BoardGoldFieldID = 7;
        public const int CoinsFieldID = 8;
        public const int RotateScoreFieldID = 9;
        public const int FlagFieldID = 10;
        public const int RewardFieldID = 11;
    }
    
    public partial class MapData
    {
        public List<Msg.Map> Maps { get; set; }
        public bool hasMaps = false;
        
        // ProtocolBuffers wire field id
        public const int MapsFieldID = 1;
    }
    
    public partial class Achievement
    {
        public string _Id { get; set; }
        public bool has_Id = false;
        
        public uint PlayerId { get; set; }
        public bool hasPlayerId = false;
        
        /// <summary>成就id</summary>
        public uint AchId { get; set; }
        public bool hasAchId = false;
        
        /// <summary>完成数量</summary>
        public uint Num { get; set; }
        public bool hasNum = false;
        
        /// <summary>状态0未完成，1已完成</summary>
        public uint State { get; set; }
        public bool hasState = false;
        
        // ProtocolBuffers wire field id
        public const int _IdFieldID = 1;
        public const int PlayerIdFieldID = 2;
        public const int AchIdFieldID = 3;
        public const int NumFieldID = 4;
        public const int StateFieldID = 5;
    }
    
    public partial class AchievementData
    {
        public List<Msg.Achievement> Achievements { get; set; }
        public bool hasAchievements = false;
        
        // ProtocolBuffers wire field id
        public const int AchievementsFieldID = 1;
    }
    
    public partial class FinishAchievement
    {
        /// <summary>成就编号</summary>
        public uint Id { get; set; }
        public bool hasId = false;
        
        // ProtocolBuffers wire field id
        public const int IdFieldID = 1;
    }
    
    public partial class DelAchievement
    {
        public uint Id { get; set; }
        public bool hasId = false;
        
        // ProtocolBuffers wire field id
        public const int IdFieldID = 1;
    }
    
    public partial class EnterMap
    {
        public uint Id { get; set; }
        public bool hasId = false;
        
        public Msg.Map Map { get; set; }
        public bool hasMap = false;
        
        // ProtocolBuffers wire field id
        public const int IdFieldID = 1;
        public const int MapFieldID = 2;
    }
    
    public partial class GameRotateStart
    {
        /// <summary>摇奖方式：1自动转，2手动转</summary>
        public uint Way { get; set; }
        public bool hasWay = false;
        
        /// <summary>id 不为0表示测试结果</summary>
        public uint Id { get; set; }
        public bool hasId = false;
        
        // ProtocolBuffers wire field id
        public const int WayFieldID = 1;
        public const int IdFieldID = 2;
    }
    
    public partial class GameRotateResult
    {
        public uint Id { get; set; }
        public bool hasId = false;
        
        public uint Power { get; set; }
        public bool hasPower = false;
        
        // ProtocolBuffers wire field id
        public const int IdFieldID = 1;
        public const int PowerFieldID = 2;
    }
    
    public partial class ShotGold
    {
        /// <summary>投币类型:1投篮，2砸箱子</summary>
        public uint Type { get; set; }
        public bool hasType = false;
        
        public Msg.Coin Coin { get; set; }
        public bool hasCoin = false;
        
        // ProtocolBuffers wire field id
        public const int TypeFieldID = 1;
        public const int CoinFieldID = 2;
    }
    
    public partial class ShotResult
    {
        /// <summary>投币类型:1投篮，2砸箱子</summary>
        public uint Type { get; set; }
        public bool hasType = false;
        
        /// <summary>1投中币的id</summary>
        public Msg.Coin Coin { get; set; }
        public bool hasCoin = false;
        
        // ProtocolBuffers wire field id
        public const int TypeFieldID = 1;
        public const int CoinFieldID = 2;
    }
    
    public partial class RGold
    {
        /// <summary>减少金币的网络id</summary>
        public uint Id { get; set; }
        public bool hasId = false;
        
        /// <summary>减少方式：0流失，1-4 进洞编号</summary>
        public uint Slot { get; set; }
        public bool hasSlot = false;
        
        /// <summary>倍率</summary>
        public uint Power { get; set; }
        public bool hasPower = false;
        
        // ProtocolBuffers wire field id
        public const int IdFieldID = 1;
        public const int SlotFieldID = 2;
        public const int PowerFieldID = 3;
    }
    
    public partial class ReduceGold
    {
        public List<Msg.RGold> Coins { get; set; }
        public bool hasCoins = false;
        
        // ProtocolBuffers wire field id
        public const int CoinsFieldID = 2;
    }
    
    public partial class PoolRotate
    {
        public uint Id { get; set; }
        public bool hasId = false;
        
        // ProtocolBuffers wire field id
        public const int IdFieldID = 1;
    }
    
    public partial class ItemChange
    {
        public List<Msg.Item> Items { get; set; }
        public bool hasItems = false;
        
        // ProtocolBuffers wire field id
        public const int ItemsFieldID = 1;
    }
    
    public partial class AddItem
    {
        public uint Id { get; set; }
        public bool hasId = false;
        
        public uint Num { get; set; }
        public bool hasNum = false;
        
        // ProtocolBuffers wire field id
        public const int IdFieldID = 1;
        public const int NumFieldID = 2;
    }
    
    public partial class AddCoins
    {
        public uint Type { get; set; }
        public bool hasType = false;
        
        public List<Msg.Coin> Coins { get; set; }
        public bool hasCoins = false;
        
        // ProtocolBuffers wire field id
        public const int TypeFieldID = 1;
        public const int CoinsFieldID = 2;
    }
    
    public partial class GoldChange
    {
        /// <summary>1签到，2进洞，3定时获得，4升级，5地图解锁,6充值购买,7投币,8购买物品</summary>
        public uint Type { get; set; }
        public bool hasType = false;
        
        /// <summary>当前金币</summary>
        public int Gold { get; set; }
        public bool hasGold = false;
        
        /// <summary>进洞的位置</summary>
        public uint Slot { get; set; }
        public bool hasSlot = false;
        
        // ProtocolBuffers wire field id
        public const int TypeFieldID = 1;
        public const int GoldFieldID = 2;
        public const int SlotFieldID = 3;
    }
    
    public partial class AddExp
    {
        public uint Exp { get; set; }
        public bool hasExp = false;
        
        // ProtocolBuffers wire field id
        public const int ExpFieldID = 1;
    }
    
    public partial class BindAccount
    {
        /// <summary>绑定账号</summary>
        public uint Account { get; set; }
        public bool hasAccount = false;
        
        /// <summary>密码</summary>
        public uint Passwd { get; set; }
        public bool hasPasswd = false;
        
        /// <summary>绑定结果：0失败，1成功,2已经绑定有账号</summary>
        public uint Result { get; set; }
        public bool hasResult = false;
        
        // ProtocolBuffers wire field id
        public const int AccountFieldID = 1;
        public const int PasswdFieldID = 2;
        public const int ResultFieldID = 3;
    }
    
    public partial class GetMapReward
    {
        public uint Id { get; set; }
        public bool hasId = false;
        
        // ProtocolBuffers wire field id
        public const int IdFieldID = 1;
    }
    
    public partial class Rank
    {
        public uint PlayerId { get; set; }
        public bool hasPlayerId = false;
        
        public string _Id { get; set; }
        public bool has_Id = false;
        
        public string Name { get; set; }
        public bool hasName = false;
        
        public uint Head { get; set; }
        public bool hasHead = false;
        
        public uint Lv { get; set; }
        public bool hasLv = false;
        
        public uint Vip { get; set; }
        public bool hasVip = false;
        
        public uint Gold { get; set; }
        public bool hasGold = false;
        
        // ProtocolBuffers wire field id
        public const int PlayerIdFieldID = 1;
        public const int _IdFieldID = 2;
        public const int NameFieldID = 3;
        public const int HeadFieldID = 4;
        public const int LvFieldID = 5;
        public const int VipFieldID = 6;
        public const int GoldFieldID = 7;
    }
    
    public partial class RankData
    {
        /// <summary>排行前50名数据</summary>
        public List<Msg.Rank> Ranks { get; set; }
        public bool hasRanks = false;
        
        /// <summary>自己的位置</summary>
        public uint Slot { get; set; }
        public bool hasSlot = false;
        
        // ProtocolBuffers wire field id
        public const int RanksFieldID = 1;
        public const int SlotFieldID = 2;
    }
    
    public partial class CsvActivity
    {
        /// <summary>活动id</summary>
        public uint Id { get; set; }
        public bool hasId = false;
        
        /// <summary>活动名字</summary>
        public string Name { get; set; }
        public bool hasName = false;
        
        /// <summary>开始时间</summary>
        public uint StartTime { get; set; }
        public bool hasStartTime = false;
        
        /// <summary>结束时间</summary>
        public uint OverTime { get; set; }
        public bool hasOverTime = false;
        
        /// <summary>活动收集目标</summary>
        public uint Target { get; set; }
        public bool hasTarget = false;
        
        /// <summary>活动数量</summary>
        public uint Num { get; set; }
        public bool hasNum = false;
        
        /// <summary>活动奖励金币</summary>
        public uint Gold { get; set; }
        public bool hasGold = false;
        
        /// <summary>描述</summary>
        public string Desc { get; set; }
        public bool hasDesc = false;
        
        /// <summary>icon</summary>
        public string Icon { get; set; }
        public bool hasIcon = false;
        
        // ProtocolBuffers wire field id
        public const int IdFieldID = 1;
        public const int NameFieldID = 2;
        public const int StartTimeFieldID = 3;
        public const int OverTimeFieldID = 4;
        public const int TargetFieldID = 5;
        public const int NumFieldID = 6;
        public const int GoldFieldID = 7;
        public const int DescFieldID = 8;
        public const int IconFieldID = 9;
    }
    
    public partial class CsvActivityData
    {
        public List<Msg.CsvActivity> Activitys { get; set; }
        public bool hasActivitys = false;
        
        // ProtocolBuffers wire field id
        public const int ActivitysFieldID = 1;
    }
    
    public partial class Activity
    {
        public string _Id { get; set; }
        public bool has_Id = false;
        
        /// <summary>玩家编号</summary>
        public uint PlayerId { get; set; }
        public bool hasPlayerId = false;
        
        /// <summary>活动编号</summary>
        public uint Id { get; set; }
        public bool hasId = false;
        
        /// <summary>活动进度</summary>
        public uint Num { get; set; }
        public bool hasNum = false;
        
        /// <summary>活动状态0 未完成，1可领，2已完成</summary>
        public uint State { get; set; }
        public bool hasState = false;
        
        // ProtocolBuffers wire field id
        public const int _IdFieldID = 1;
        public const int PlayerIdFieldID = 2;
        public const int IdFieldID = 3;
        public const int NumFieldID = 4;
        public const int StateFieldID = 5;
    }
    
    public partial class BuyBill
    {
        /// <summary>订单号</summary>
        public string _Id { get; set; }
        public bool has_Id = false;
        
        /// <summary>玩家</summary>
        public uint PlayerId { get; set; }
        public bool hasPlayerId = false;
        
        /// <summary>所在服务器</summary>
        public uint Sn { get; set; }
        public bool hasSn = false;
        
        /// <summary>购买编号</summary>
        public uint Buyid { get; set; }
        public bool hasBuyid = false;
        
        /// <summary>下订单时间</summary>
        public uint Time { get; set; }
        public bool hasTime = false;
        
        /// <summary>订单价值 $美元</summary>
        public float Money { get; set; }
        public bool hasMoney = false;
        
        /// <summary>获得金币</summary>
        public uint Gold { get; set; }
        public bool hasGold = false;
        
        // ProtocolBuffers wire field id
        public const int _IdFieldID = 1;
        public const int PlayerIdFieldID = 2;
        public const int SnFieldID = 3;
        public const int BuyidFieldID = 4;
        public const int TimeFieldID = 5;
        public const int MoneyFieldID = 6;
        public const int GoldFieldID = 7;
    }
    
    public partial class FinishGuide
    {
        public uint Id { get; set; }
        public bool hasId = false;
        
        // ProtocolBuffers wire field id
        public const int IdFieldID = 1;
    }
    
    public partial class GetGiftWord
    {
        public string Word { get; set; }
        public bool hasWord = false;
        
        // ProtocolBuffers wire field id
        public const int WordFieldID = 1;
    }
    
    public enum MsgId
    {
        /// <summary>心跳包</summary>
        ID_HeartBeat = 1,
        /// <summary>登陆     			</summary>
        ID_Login = 2,
        /// <summary>最新版本号</summary>
        ID_SrvVersion = 3,
        /// <summary>服务器时间同步</summary>
        ID_MsgServerTime = 4,
        /// <summary>角色信息申请</summary>
        ID_PlayerInfo = 5,
        /// <summary>创建角色</summary>
        ID_CreatePlayer = 6,
        /// <summary>购买物品</summary>
        ID_BuyItem = 7,
        /// <summary>使用物品</summary>
        ID_UseItem = 9,
        /// <summary>条框消息提示</summary>
        ID_MsgTip = 10,
        /// <summary>获取服务器压力较少的服务器</summary>
        ID_GameServer = 11,
        /// <summary>vip信息</summary>
        ID_VipInfo = 12,
        /// <summary>领取时间金币</summary>
        ID_GetTimeGold = 13,
        /// <summary>邮件信息</summary>
        ID_EmailData = 14,
        /// <summary>邮件信息修改</summary>
        ID_Email = 15,
        /// <summary>读邮件</summary>
        ID_ReadEmail = 16,
        /// <summary>获取邮件附件</summary>
        ID_GetEmailItem = 17,
        /// <summary>删除邮件</summary>
        ID_DeleteEmail = 18,
        /// <summary>修改头像</summary>
        ID_ModifyHead = 20,
        /// <summary>修改名字</summary>
        ID_ModifyNickName = 21,
        /// <summary>转盘</summary>
        ID_Rotate = 22,
        /// <summary>成就</summary>
        ID_Achievement = 23,
        /// <summary>成就数据</summary>
        ID_AchievementData = 24,
        /// <summary>完成成就</summary>
        ID_FinishAchievement = 25,
        /// <summary>地图数据</summary>
        ID_MapData = 27,
        /// <summary>地图</summary>
        ID_Map = 28,
        /// <summary>进入地图</summary>
        ID_EnterMap = 29,
        /// <summary>退出地图</summary>
        ID_ExitMap = 30,
        /// <summary>游戏中摇奖</summary>
        ID_GameRotateStart = 31,
        /// <summary>摇奖结果</summary>
        ID_GameRotateResult = 32,
        /// <summary>摇奖结束</summary>
        ID_GameRotateOver = 33,
        /// <summary>投入金币</summary>
        ID_ShotGold = 34,
        /// <summary>减少桌面金币</summary>
        ID_ReduceGold = 36,
        /// <summary>中彩金转奖</summary>
        ID_PoolRotate = 37,
        /// <summary>道具</summary>
        ID_Item = 38,
        ID_ItemData = 39,
        ID_DeleteItem = 40,
        ID_ItemChange = 41,
        /// <summary>添加道具，调试用</summary>
        ID_AddItem = 42,
        ID_AddCoins = 43,
        ID_ShotResult = 44,
        ID_PlayerDetail = 45,
        ID_ShotBox = 46,
        ID_ReqGold = 47,
        ID_GoldChange = 48,
        ID_AddExp = 49,
        /// <summary>转彩金结束发送</summary>
        ID_PoolRotateOver = 50,
        /// <summary>绑定账号</summary>
        ID_BindAccount = 51,
        ID_DelAchievement = 52,
        ID_GetMapReward = 53,
        ID_RankData = 54,
        ID_Activity = 55,
        ID_CsvActivity = 56,
        ID_CsvActivityData = 57,
        ID_FinishActivity = 58,
        /// <summary>购买订单</summary>
        ID_BuyBill = 59,
        /// <summary>领取免费定时金币</summary>
        ID_GetFreeGold = 60,
        /// <summary>一推到底结束</summary>
        ID_PushAll = 61,
        /// <summary>完成引导</summary>
        ID_FinishGuide = 62,
        /// <summary>激活码领取奖励</summary>
        ID_GetGiftWord = 63,
        /// <summary>删除活动</summary>
        ID_DelActivity = 64,
    }
    
    
}
